pipeline {

    agent any

    environment { 
        CICDTask = 'HellowWord'
    }

    stages {
        stage('STAGE 00'){
            steps{

                echo "Pipeline Usando Jenkinsfile"
            }
        }

        stage('STAGE 01'){

            steps{

                echo "Pipeline Usando Jenkinsfile"

            }
        }
    }
}
